### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by blue-j** [loic911/CBIRestAPI#2]
Thank you so much for your work!  I am eager to try this.  Unfortunately I am not very familiar with Java.  When I try to install, I get this:

MyComputer:CBIRest-0.2.1 blue-j$ sudo java -jar retrieval-0.2.1-SNAPSHOT.war --spring.profiles.active=prod --retrieval.store.name=MEMORY
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/cbir/retrieval/Application : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:163)
    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
    at java.lang.Thread.run(Thread.java:695)

How to handle this?  I am running Java 8, update 60, on Mac OS 10.10.5.

Thank you so much in advance!!  - J

**Comment by loic911** [comment]
Strange, it seems to be a conflict with your java version. Can you copy/paste the content of a 
    java -version

**Comment by blue-j** [comment]
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)

**Comment by blue-j** [comment]
Yet in the browser I get
You have the recommended Java installed (Version 8 Update 60).

At first glance it looks like I have two Javas installed?  Sorry I am totally new to this!

**Comment by blue-j** [comment]
After installing the Java SDK, my CLI version matched and installation was successful.  Thank you for your time! I'm grateful and excited to see your work!

**Comment by loic911** [comment]
You're welcome ;-)
